ARG LT_VER=5.5
FROM registry.access.redhat.com/ubi8/ubi-minimal:8 as stage1
ARG LT_VER

RUN microdnf -y install git maven unzip nginx java-1.8.0-openjdk-headless; microdnf clean all; 
RUN git clone --depth 5 https://github.com/languagetool-org/languagetool.git /opt/languagetool/
WORKDIR /opt/languagetool/

RUN mvn clean
# Don't use the shell script, just run the maven command with quiet to silence the wall of text
RUN mvn -q --projects languagetool-standalone --also-make package -DskipTests
# Copy the server jar to a generic location
RUN cp $(find /opt/languagetool/ -iname "languagetool-server.jar") /languagetool-server.jar

FROM registry.hub.docker.com/library/alpine:3 as stage2

RUN apk add --no-cache openjdk8-jre

COPY --from=stage1 /languagetool-server.jar /opt/languagetool/languagetool-server.jar
COPY --chmod=755 startup.sh /opt/languagetool/startup.sh

USER root
RUN adduser -S lang
USER lang

EXPOSE 8080/tcp
HEALTHCHECK --interval=2m --start-period=5m --timeout=5s CMD curl -f http://localhost:8080/v2/languages || exit 1
CMD /opt/languagetool/startup.sh
